title: First Project
logo: /assets/headshot_circle.jpg
description: Forward-thinking strategist dedicated to leveraging synergies for sustainable growth
show_downloads: true
theme: jekyll-theme-minimal
