title: First Project
teaser: ![](/assets/headshot_circle.png)
logo: assets/headshot_circle.png
description: Forward-thinking strategist dedicated to leveraging synergies for sustainable growth
# show_downloads: true
theme: jekyll-theme-minimal
