title: First Project
# logo: /assets/img/headshot_circle.png
description: Forward-thinking strategist dedicated to leveraging synergies for sustainable growth
show_downloads: true
theme: jekyll-theme-minimal
